SELECT p.`PRODUCT_CODE`, sum(p.`PRICE`* o.`SALES_AMOUNT`) as SALES
from PRODUCT p
join OFFLINE_SALE o on p.`PRODUCT_ID` = o.`PRODUCT_ID`
group BY p.`PRODUCT_CODE`
ORDER BY SALES desc, p.`PRODUCT_CODE` asc