-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, 
date_format(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE

from USED_GOODS_BOARD b
join USED_GOODS_REPLY r on b.BOARD_ID = r.BOARD_ID 
where DATE_FORMAT(b.CREATED_DATE, '%Y%m') = '202210'
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC